# ============================ #
# What a sigma-algebra decides: the one generated by a partition ####
# ============================ #
#
# Claim. A sigma-algebra fixes which sets can be spoken of and therefore which functions can be
# described. For the partition of a set into n cells, the sigma-algebra it generates has exactly
# 2^n members, a function is measurable with respect to it exactly when it is constant on every
# cell, and the best that any measurable function can do against a given f is the conditional
# expectation, the average of f over each cell. For f(x) = x on the unit interval with n equal
# cells that best is the midpoint, and the error it leaves has the closed form
#
#     || f - E[f | P_n] ||_2 = 1 / (2 sqrt(3) n),
#
# derived here: the square of the error is the sum over the cells of the integral of (x - mid)^2,
# which is n times h^3/12 with h = 1/n, that is 1/(12 n^2). The case n = 1 is the trivial
# sigma-algebra, where the only measurable functions are the constants and the error is the
# standard deviation of f.
#
# Method and references, none of which shares the code under test.
#   1. The count 2^n, by closing the cells under complement and union on a finite ground set and
#      counting what comes out, against the closed form.
#   2. The characterisation of the measurable functions, by testing the definition directly, that
#      the preimage of every value lies in the sigma-algebra, against the criterion of being
#      constant on each cell, and both against the closed form v^n.
#   3. The error of the conditional expectation, by quadrature against the closed form above.
#   4. The minimality of the conditional expectation, by searching over measurable competitors and
#      against the derived identity that the excess is the squared distance to the average.
#   5. A second function with no symmetry, against adaptive quadrature.
#
# Degenerate cases: the trivial sigma-algebra and the discrete one.

set.seed(20260920L)

emit <- function(id, status, summary, metrics) {
    val <- function(v) if (is.character(v)) sprintf("\"%s\"", v) else if (!is.finite(v)) "null" else formatC(v, digits = 6, format = "g")
    fields <- paste(sprintf("\"%s\": %s", names(metrics), vapply(metrics, val, character(1))), collapse = ", ")
    cat(sprintf("{\"id\": \"%s\", \"status\": \"%s\", \"summary\": \"%s\", \"metrics\": {%s}}\n", id, status, summary, fields))
}

# ============================ #
# Test 1: the sigma-algebra generated by a partition ####
# ============================ #
#
# The ground set has m points and the partition has n cells. A subset is a bitmask. The closure
# is taken under complement and pairwise union until nothing new appears, which is the definition
# applied literally, and the count is compared with 2^n.

generated_size <- function(cells, m) {
    full <- bitwShiftL(1L, m) - 1L
    seen <- unique(c(0L, full, cells))
    repeat {
        new <- unique(c(bitwAnd(bitwNot(seen), full),
                        as.vector(outer(seen, seen, bitwOr))))
        both <- unique(c(seen, new))
        if (length(both) == length(seen)) break
        seen <- both
    }
    length(seen)
}

test_generated <- function(n_max = 10L) {
    rows <- list()
    for (n in 1:n_max) {
        m <- n + 2L                              # two cells hold two points, the rest one
        sizes <- c(rep(1L, n - 1L), m - (n - 1L))
        idx <- split(seq_len(m), rep(seq_len(n), sizes))
        cells <- vapply(idx, function(p) sum(bitwShiftL(1L, p - 1L)), numeric(1))
        rows[[length(rows) + 1L]] <- data.frame(
            cells = n, points = m, size = generated_size(as.integer(cells), m),
            closed_form = 2^n, stringsAsFactors = FALSE)
    }
    do.call(rbind, rows)
}

# ============================ #
# Test 2: which functions the sigma-algebra can describe ####
# ============================ #
#
# Every function from a ground set of m points to v values is enumerated. One route asks the
# definition, that the preimage of each value belongs to the sigma-algebra; the other asks that
# the function be constant on each cell. The two sets must agree, and their size must be v^n.

test_measurable <- function(m = 6L, n = 3L, v = 3L) {
    # the m points are shared out over the n cells as evenly as the numbers allow
    sizes <- rep(m %/% n, n); if (m %% n > 0L) sizes[seq_len(m %% n)] <- sizes[seq_len(m %% n)] + 1L
    idx <- split(seq_len(m), rep(seq_len(n), sizes))
    cells <- vapply(idx, function(p) sum(bitwShiftL(1L, p - 1L)), numeric(1))
    full <- bitwShiftL(1L, m) - 1L
    algebra <- local({
        seen <- unique(c(0L, full, as.integer(cells)))
        repeat {
            new <- unique(c(bitwAnd(bitwNot(seen), full), as.vector(outer(seen, seen, bitwOr))))
            both <- unique(c(seen, new))
            if (length(both) == length(seen)) break
            seen <- both
        }
        seen
    })
    grid <- as.matrix(expand.grid(rep(list(seq_len(v)), m)))
    by_definition <- apply(grid, 1, function(f) {
        all(vapply(seq_len(v), function(a) {
            mask <- sum(bitwShiftL(1L, which(f == a) - 1L))
            as.integer(mask) %in% algebra
        }, logical(1)))
    })
    by_constancy <- apply(grid, 1, function(f) all(vapply(idx, function(p) length(unique(f[p])) == 1L, logical(1))))
    list(functions = nrow(grid), by_definition = sum(by_definition),
         by_constancy = sum(by_constancy), agree = all(by_definition == by_constancy),
         closed_form = v^n, algebra_size = length(algebra))
}

# ============================ #
# Test 3: the error that the sigma-algebra leaves ####
# ============================ #

cell_average <- function(f, a, b, n_quad = 4096L) {
    x <- a + (seq_len(n_quad) - 0.5) * (b - a) / n_quad
    mean(f(x))
}

l2_error <- function(f, n, n_quad = 4096L) {
    edges <- seq(0, 1, length.out = n + 1L)
    tot <- 0
    for (k in seq_len(n)) {
        a <- edges[k]; b <- edges[k + 1L]
        avg <- cell_average(f, a, b, n_quad)
        x <- a + (seq_len(n_quad) - 0.5) * (b - a) / n_quad
        tot <- tot + mean((f(x) - avg)^2) * (b - a)
    }
    sqrt(tot)
}

test_error <- function(ns) {
    id <- function(x) x
    rows <- lapply(ns, function(n) data.frame(
        n = n, measured = l2_error(id, n), closed_form = 1 / (2 * sqrt(3) * n)))
    do.call(rbind, rows)
}

# ============================ #
# Test 4: the conditional expectation is the best the sigma-algebra allows ####
# ============================ #
#
# A competitor is any function constant on the cells, that is any vector of n values. The excess
# of its squared error over that of the conditional expectation is the squared distance between
# the two vectors, weighted by the cell widths, which the test checks against a direct
# computation as well as against a random search.

test_minimality <- function(n = 8L, trials = 400L) {
    id <- function(x) x
    edges <- seq(0, 1, length.out = n + 1L)
    mids <- (edges[-1] + edges[-(n + 1L)]) / 2
    h <- 1 / n
    base <- l2_error(id, n)^2
    worst_gap <- Inf; max_identity_error <- 0
    for (t in seq_len(trials)) {
        g <- mids + rnorm(n, 0, 0.3)
        tot <- 0
        for (k in seq_len(n)) {
            x <- edges[k] + (seq_len(2048L) - 0.5) * h / 2048
            tot <- tot + mean((x - g[k])^2) * h
        }
        predicted <- base + sum((g - mids)^2) * h
        max_identity_error <- max(max_identity_error, abs(tot - predicted))
        worst_gap <- min(worst_gap, tot - base)
    }
    list(base = base, smallest_excess = worst_gap, identity_error = max_identity_error)
}

# ============================ #
# Test 5 and 6: a second function, and the two degenerate sigma-algebras ####
# ============================ #

test_second <- function(ns) {
    f <- function(x) sin(2 * pi * x) + x^2
    exact <- function(n) {
        edges <- seq(0, 1, length.out = n + 1L)
        tot <- 0
        for (k in seq_len(n)) {
            a <- edges[k]; b <- edges[k + 1L]
            avg <- integrate(f, a, b, rel.tol = 1e-12)$value / (b - a)
            tot <- tot + integrate(function(x) (f(x) - avg)^2, a, b, rel.tol = 1e-12)$value
        }
        sqrt(tot)
    }
    rows <- lapply(ns, function(n) data.frame(n = n, measured = l2_error(f, n), quadrature = exact(n)))
    out <- do.call(rbind, rows)
    out$ratio <- out$quadrature * out$n
    out
}

test_degenerate <- function() {
    id <- function(x) x
    trivial <- l2_error(id, 1L)
    sd_of_f <- sqrt(integrate(function(x) (x - 0.5)^2, 0, 1, rel.tol = 1e-12)$value)
    disc <- test_measurable(m = 4L, n = 4L, v = 2L)
    data.frame(trivial_error = trivial, standard_deviation = sd_of_f,
               discrete_measurable = disc$by_definition, discrete_total = disc$functions)
}

# ============================ #
# Run ####
# ============================ #

t_gen <- test_generated()
t_meas <- test_measurable()
t_err <- test_error(c(1L, 2L, 4L, 8L, 16L, 64L, 256L))
t_min <- test_minimality()
t_sec <- test_second(c(2L, 4L, 8L, 16L, 32L))
t_deg <- test_degenerate()

ok_gen <- all(t_gen$size == t_gen$closed_form)
ok_meas <- t_meas$agree && t_meas$by_definition == t_meas$closed_form
# The quadrature uses the midpoint rule on 4096 nodes per cell, whose error on a quadratic is of
# order the square of the node spacing, so one part in a million of the value is ample.
ok_err <- max(abs(t_err$measured - t_err$closed_form) / t_err$closed_form) < 1e-6
ok_min <- t_min$smallest_excess > 0 && t_min$identity_error < 1e-9
ok_sec <- max(abs(t_sec$measured - t_sec$quadrature) / t_sec$quadrature) < 1e-6 &&
          all(diff(t_sec$quadrature) < 0)
# The midpoint rule on N nodes integrates a quadratic with an error of (b - a) h^2 |g''| / 24,
# which for (x - 1/2)^2 on the unit interval and N = 4096 is 5 * 10^-9 in the square of the
# distance and so about 10^-8 in the distance itself; the comparison allows ten times that.
ok_deg <- abs(t_deg$trivial_error - t_deg$standard_deviation) < 1e-7 &&
          t_deg$discrete_measurable == t_deg$discrete_total

status <- if (ok_gen && ok_meas && ok_err && ok_min && ok_sec && ok_deg) "pass" else "fail"

# ============================ #
# Figure ####
# ============================ #

if (requireNamespace("ggplot2", quietly = TRUE) && requireNamespace("patchwork", quietly = TRUE)) {
    source("checks/lib/figure-style.R")
    suppressPackageStartupMessages({ library(ggplot2); library(patchwork) })
    f2 <- function(x) sin(2 * pi * x) + x^2
    xs <- seq(0, 1, length.out = 1200)
    steps <- do.call(rbind, lapply(c(2L, 4L, 8L, 16L), function(n) {
        edges <- seq(0, 1, length.out = n + 1L)
        do.call(rbind, lapply(seq_len(n), function(k) {
            avg <- cell_average(f2, edges[k], edges[k + 1L])
            data.frame(n = kb_unicode(sprintf("$n = %d$", n)),
                       x = c(edges[k], edges[k + 1L]), y = avg, cell = k,
                       stringsAsFactors = FALSE)
        }))
    }))
    curve <- do.call(rbind, lapply(unique(steps$n), function(l)
        data.frame(n = l, x = xs, y = f2(xs), stringsAsFactors = FALSE)))
    steps$n <- factor(steps$n, levels = unique(steps$n))
    curve$n <- factor(curve$n, levels = levels(steps$n))
    pa <- ggplot() +
        geom_line(data = curve, aes(x, y), colour = "grey55", linewidth = 0.5) +
        geom_line(data = steps, aes(x, y, group = interaction(n, cell)), colour = "#056796",
                  linewidth = 0.9) +
        facet_wrap(~ n, nrow = 1) +
        labs(subtitle = kb_unicode("A function in grey, and the best that the sigma-algebra of $n$ equal cells can say about it"),
             x = kb_tex("$x$"), y = kb_tex("$f(x)$")) +
        kb_theme()
    fine <- 2^seq(0, 9, by = 0.05)
    line <- data.frame(n = fine, err = 1 / (2 * sqrt(3) * fine))
    pts <- data.frame(n = t_err$n, err = t_err$measured)
    pb <- ggplot(line, aes(n, err)) +
        geom_line(colour = "#be1117", linewidth = 0.6) +
        geom_point(data = pts, aes(n, err), size = 2, shape = 21, fill = "white",
                   colour = "#056796", stroke = 0.7) +
        scale_x_log10() + scale_y_log10() +
        labs(subtitle = kb_unicode("What the sigma-algebra leaves out, for $f(x) = x$, against the closed form"),
             x = kb_tex("Cells $n$"), y = kb_tex("$\\|f - E[f \\mid P_n]\\|_2$")) +
        kb_theme()
    fig <- (pa / pb) + plot_layout(heights = c(1, 1)) +
        plot_annotation(
            title = kb_unicode("What a sigma-algebra decides"),
            caption = kb_caption(paste(
                "Upper: the function $f(x) = \\sin(2\\pi x) + x^2$ in grey and its conditional expectation on",
                "the sigma-algebra generated by $n$ equal cells in blue, which is the average of $f$ over each",
                "cell and the closest any measurable function comes to it. Lower: for $f(x) = x$ the distance",
                "left over is exactly $1/(2\\sqrt{3}n)$, the line, and the circles are the computed values at",
                "seven resolutions; the first is the trivial sigma-algebra, where the only measurable",
                "functions are the constants and the distance is the standard deviation of $f$. Drawn by",
                "checks/sigma-algebra-of-a-partition.R.")),
            theme = kb_theme())
    kb_save(fig, "sigma-algebra-of-a-partition", width = 8.6, height = 5.4)
}

emit("sigma-algebra-of-a-partition", status,
     "The sigma-algebra generated by n cells has 2^n members, its measurable functions are those constant on the cells, and the distance it leaves to f(x) = x is 1/(2 sqrt(3) n)",
     list(partitions_tested = nrow(t_gen),
          largest_sigma_algebra = max(t_gen$size),
          counts_match_two_to_the_n = as.numeric(ok_gen),
          functions_enumerated = t_meas$functions,
          measurable_by_definition = t_meas$by_definition,
          measurable_by_constancy = t_meas$by_constancy,
          measurable_closed_form = t_meas$closed_form,
          error_cases = nrow(t_err),
          max_relative_error_against_the_closed_form = max(abs(t_err$measured - t_err$closed_form) / t_err$closed_form),
          error_at_one_cell = t_err$measured[t_err$n == 1],
          standard_deviation_of_f = t_deg$standard_deviation,
          error_at_256_cells = t_err$measured[t_err$n == 256],
          smallest_excess_over_the_conditional_expectation = t_min$smallest_excess,
          minimality_identity_error = t_min$identity_error,
          second_function_max_relative_error = max(abs(t_sec$measured - t_sec$quadrature) / t_sec$quadrature),
          discrete_sigma_algebra_measurable = t_deg$discrete_measurable,
          discrete_sigma_algebra_total = t_deg$discrete_total))
